### ISSUE TITLE
Not moving to double characters position

### ISSUE THREAD

**Issue by lekhnath** [metaseed/metaGo#1]
I recently updated this to v1.15.0 and experienced this issue. Cursor is not moving to the double characters position but works fine with single character position. I mean when there are lots of matches and this extension shows two characters (ie. `kj`) and when I type `k` and then `j` the cursor is not moving to that place.

VSCode v1.11.1
Thanks.

**Comment by metasong** [comment]
wow! first issue report, thanks!
sorry for the mistake bug, fixed in new version.
I added intleliget goto features and goto previous/next features in new version
