### ISSUE TITLE
Theme Configuration

### ISSUE THREAD

**Issue by piox34** [metaseed/metaGo#13]
Loving the package, really useful! I was wondering if there would be a chance to configure the box color and size - jumpy in Atom picks the editor theme which fits really nicely with everything.

Might not be top priority but would make it much nicer to look at. Many thanks for considering this!

**Comment by metasong** [comment]
thanks for your feedback:

you could do it in your vscode setting:
![image](https://user-images.githubusercontent.com/5009757/47066551-16014f00-d219-11e8-84fa-ed6dac53c318.png)
