### ISSUE TITLE
Place cursot not after but before letter

### ISSUE THREAD

**Issue by ColCh** [metaseed/metaGo#17]
given: `k` letter pressed

![image](https://user-images.githubusercontent.com/599439/47503602-35305a00-d873-11e8-82c4-65bab2168cd4.png)

then user pressed on `j`

cursor moves here

![image](https://user-images.githubusercontent.com/599439/47503671-5b55fa00-d873-11e8-93df-bbabbe56f277.png)

and the question is, how to make it move here instead?

![image](https://user-images.githubusercontent.com/599439/47503730-7aed2280-d873-11e8-82d0-8d2211f29a9d.png)

hey, is it's impossible - I'm able to send PR to implement such setting

**Comment by ColCh** [comment]
It seemed that I should use other command

**Comment by art049** [comment]
I'm interested if you found a way to do it @ColCh

**Comment by ColCh** [comment]
@art049 

there are commands for it

just try to use one of these

https://github.com/metaseed/metaGo/blob/0422537c5750c50283e0950d986c89221d076291/package.json#L45-L48

https://github.com/metaseed/metaGo/blob/0422537c5750c50283e0950d986c89221d076291/package.json#L49-L52

https://github.com/metaseed/metaGo/blob/716a4872b6f92fb4fe6423d63a0812a220e909f6/src/metajumper/index.ts#L52
