### ISSUE TITLE
[enhancement] Option to add code labels only to beginning of words

### ISSUE THREAD

**Issue by iignatov** [metaseed/metaGo#19]
It would be great if there's a configuration setting to add code labels only to beginning of words. IMO this is the main use-case (or at least I use it only this way). This will vastly reduce the clutter when trying to navigate to a word that starts with a very common character (which gets even worse when the word contains it multiple times).

**Comment by metasong** [comment]
@iignatov what is IMO? 
is this related to #20

**Comment by metasong** [comment]
close this because have config to do this already:
```
				"metaGo.jumper.findAllMode": {
					"type": "string",
					"default": "on",
					"description": "on: find all characters on viewable screen area; off: only search the first character of the words that are separated by chars configured in 'wordSeparatorPattern'"
				},
				"metaGo.jumper.wordSeparatorPattern": {
					"type": "string",
					"default": "[ ,-.{_(\"'<\\/[+]"
				},
```
