### ISSUE TITLE
Moving cursor up/down, skipping whitespace

### ISSUE THREAD

**Issue by plievone** [metaseed/metaGo#2]
Hi! A quick drive-by suggestion: moving up/down using whitespace is even more useful if you would take column into account, so one could use current indentation to affect the granularity of movement. Some explanation here: https://github.com/Microsoft/vscode/issues/16367

It may need experimentation, but basically skipping up/down to next char before whitespace (if already on a char), or next char after whitespace (if already on a whitespace). Where whitespace means whitespace at the beginning or at the end of line. Needs to keep column state in memory, so that skipping won't stop at empty lines etc (where cursor column position is lower than intended). Wrapped lines may be a problem for you, however.

This kind of skipping movement is very convenient as one can decrease cursor indentation with home-key to start skipping among beginning/end of control structures, functions, modules etc easily, and usually one finds navigating to other lines is also easy as one can go further in the line and skip to a long line near the target line in question. Combined with intelligent horizontal movement such as word-and-delimiter-skipping, which might be a good fit to this extension at some point, it makes a good default movement for many. Thanks!

**Comment by metasong** [comment]
let me have try, i've will give further information later.
