### ISSUE TITLE
[enhancement] Incremental word navigation

### ISSUE THREAD

**Issue by iignatov** [metaseed/metaGo#20]
It would be awesome to add ability to incrementally filter word navigation, e.g. when someone wants to navigate to the word `awesome` starting with `a` adds labels to all occurrences of `a`, then typing `w` leaves labels only the at places which contains `aw`, etc...

**Comment by metasong** [comment]
what's the benefits compared with current way?

this way is more like a search, try ctrl+f then type?
close it for now

**Comment by iignatov** [comment]
IMHO the current way is very confusing - if one hits a very common letter, there are so many labels that they add much more noise than usefulness.

When I tried to use this plugin I constantly was entering 2-3 letters of the word in a row, which sometimes resulted in jumps in totally different locations.

I stopped using this plugin because of that - at least for me the current way is not working at all.

**Comment by metasong** [comment]
@iignatov you mean the current encoding way has flaw to lead you to wrong location? I would examining the algorithm, and make it better.

YES! you are right, I'm trying to add the muti-location char support, take your example, that means you could type aw... and the decoration code would dynamically changed accordingly. with this way you have 2 sets of codes for locating, one follows the location char, one generated as decoration. you could always type the chars follows and at any time type the decoration codes if you want.

just finished the hold/release '/' to hide/show decorators feature.
currently I'm trying to make it support all opened editors
after that is the muti location chars feature. 

-----
I think at that time, you must be come back😉

**Comment by metasong** [comment]
done!
V3.4.0 - Mar 18, 2020
