### ISSUE TITLE
command 'metaGo.delete.softDelete' not found

### ISSUE THREAD

**Issue by janhesters** [metaseed/metaGo#22]
I'm used to hitting `shift`+`backspace` when editing files, especially when I misspell constants.

After installing this extensions it doesn't erase my last typed character, but instead it shows the error message:

```
command 'metaGo.delete.softDelete' not found
```

This seems to be a bug.  I can't find anything about that setting in the docs.

**Comment by flowchartsman** [comment]
Could use some guidance on this one. It seems to be in the source, but I see references to imports commented out. It's pretty rough having a prebound command that doesn't exist and removes existing functionality in VScode. I'm happy at taking a crack at a fix, but I'm not experienced in typescript, and, given that this has been a problem for 9 months now, it's not inspiring a lot of confidence, so I can't recommend this extension to anyone.

**Comment by TheAifam5** [comment]
It's not a bug. Just got deleted 1yr ago :)

**Comment by metasong** [comment]
I would enhance delete related feature recently, sorry for the half implemented feature

**Comment by metasong** [comment]
totally remove the feature implementation, recommend the hungry-delete extension
