### ISSUE TITLE
Missing metaGo.gotoInteli command?

### ISSUE THREAD

**Issue by pkazmier** [metaseed/metaGo#25]
The `metaGo.gotoInteli` command is missing and does not appear in the command palette or the contributed commands section in the MetaGo extension description. Is this because the command is not registered in `package.json` in the `contributes` section?

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/747855/58571309-175b1700-81ff-11e9-847c-a27969ccb5e9.png">

Could you push a new version up? I'd much rather bind Alt+; to the inteli version of the command instead of having to remember Alt+; or Ctrl+Alt+; 

Thanks for an amazing plug-in. As a keyboard junkie, this is a life saver!

**Comment by freMea** [comment]
It is not listed in panel but it appears in keyboard shortcuts and can be assigned.

**Comment by metasong** [comment]
fixed, in v3
