### ISSUE TITLE
Assigning keybindings sequence doesn’t work

### ISSUE THREAD

**Issue by freMea** [metaseed/metaGo#26]
VS Code version | OS | Extension version
------------------ | ---- | ----
1.37.1 | Win 10 x64 pro (french) 18362 | 2.11.0

## Steps to reproduce

1. assign a valid and free keybindings sequence like CTRL+K SHIFT+ARROWDOWN for selectLineDown
2. test it

## Results

A warning message is displayed in the Code status bar “The key combination…is not a command”

**Comment by metasong** [comment]
have to reload the window to take effect. with your shortcut, I would rethink about this command
