### ISSUE TITLE
Destination letters not appearing.

### ISSUE THREAD

**Issue by Ch3ri0ur** [metaseed/metaGo#28]
When using VSCode Insiders the destination letters don't appear anymore. 
It switches to the Jump-Mode, you can see a green bar at your current location, but the other letters are missing.

If you then press some likely keys the courser jumps.
So it seem it's really just the display.

I'm currently using VSCode Insiders Version 1.39.0
I disabled all other extensions but the problem persisted.
When using the normal Version (1.38.1) metaGo works as it should.

**Comment by kamenminkov** [comment]
Can confirm, the issue exists in the latest few Insider builds.

**Comment by kamenminkov** [comment]
Seems to be fixed in today's Insider build.

**Comment by kamenminkov** [comment]
Issue is present again in latest Insider 1.40.0 build.

**Comment by Ch3ri0ur** [comment]
Can confirm. Same issues in 1.40.0.

**Comment by nicchristeller** [comment]
Have added a PR that works around the problem, since I'm unsure of the actual cause. If this gets no attention in the very near future (the repo may have been abandoned?) then I'll figure out how to set up my fork as a full-fledged extension for VSCode.

**Comment by AaronDovTurkel** [comment]
> Have added a PR that works around the problem, since I'm unsure of the actual cause. If this gets no attention in the very near future (the repo may have been abandoned?) then I'll figure out how to set up my fork as a full-fledged extension for VSCode.

Also not showing for me...

**Comment by nicchristeller** [comment]
With the PR applied? You'll need to add a setting `metaGo.decoration.useTextBasedDecorations: true` since I've left it off by default to be less intrusive

**Comment by AaronDovTurkel** [comment]
Nope - not sure how to apply the PR...

**Comment by nicchristeller** [comment]
My fork is and appears to be working, at https://marketplace.visualstudio.com/items?itemName=metagogo.metagogo. Ignore my comment above, it should automatically work without adding any settings values. Let me know how it goes for the rest of you!

**Comment by kamenminkov** [comment]
Cool! Thank you very much!
Just tried it on 1.41 Insider, it does indeed work. Decorators look a little more jagged and somewhat misplaced, but of course this is way better than nothing.

**Comment by nicchristeller** [comment]
Yep, it will probably get some polish when I find some spare time but just wanted it up and running for now 😅

**Comment by tiancai110a** [comment]
> should

it work!

**Comment by kbirger** [comment]
@nicchristeller your fork doesn't work for me.

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

same behavior as original. 

I hit alt+;, and I get a small green rectangle highlight. I press any key, and the input cursor jumps around a little bit, then returns to original position.

**Comment by metasong** [comment]
thank the pull request from @nicchristeller , new version released, I would do more improvement for the project from now on...
@nicchristeller would you like to be a codeveloper for this project?
