### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by n-roman** [metaseed/metaGo#3]
When I press any extension specific shortcut or choose a command from command palette I got an error: "command 'metaGo.goto' not found".

VSCode:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by metasong** [comment]
I've tested  metago extension (V1.23.0) on the VSCode (1.11.2) and can't repeat the problem. can you give me more detail information?

**Comment by n-roman** [comment]
I have recently installed Fedora 25 and fresh version vscode from official repo. I removed ~/.vscode and ~/.config/Code for this test, so I have no other extensions and default settings.
1. Start VsCode
2. Install metaGo extension
3. Reload VsCode
4. Open Command Palette
5. Choose metaGo Goto command

![image](https://cloud.githubusercontent.com/assets/1137252/25193287/40089246-253f-11e7-82a8-671b1631d273.png)

**Comment by OldViking** [comment]
Right after install plugin i had the same issue. I'm typing Alt+; and get warning message "command 'MetaGo' not found". Also i had error "Activating extension `metaseed.metago` failed:  config.get(...).split is not a function" in developer tools.

OS: Windows 10 
VS Code version 1.11.2

**Comment by n-roman** [comment]
I have other errors in console:

```
extensionHost.ts:284[Extension Host] Activating extension `metaseed.metago` failed: Cannot find module './bookmark'.d.logExtensionHostMessage @ extensionHost.ts:284

extensionHost.ts:284[Extension Host] Activating extension `metaseed.metago` failed:  Cannot find module './bookmark'd.logExtensionHostMessage @ extensionHost.ts:284

extensionHost.ts:284[Extension Host] Here is the error stack:  Error: Cannot find module './bookmark'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/roman/.vscode/extensions/metaseed.metago-1.23.0/out/src/bookmark/index.js:6:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

mainThreadExtensionService.ts:111Activating extension `metaseed.metago` failed: Cannot find module './bookmark'.
```

**Comment by metasong** [comment]
it seems the error comes from wrong configuration of metaGo.decoration.characters.
the default one is "k, j, d, f, l, s, a, h, g, i, o, n, u, r, v, c, w, e, x, m, b, p, q, t, y, z". it's a string.
in new release, i've make sure metaGo will run with default config, even if user gives wrong configuration. and the user will be notified when config is wrong.

@n-roman @OldViking, thank you very much for your detail information.
please try the new version, any problem, keep in touch!!

**Comment by n-roman** [comment]
Sorry, but it's not fixed in 1.24.0.
I think first problem is that file src/bookmark/index has import './bookmark', but the real file has name Bookmark.
Linux file systems are case sensitivity.
Still not work, there is some another problem, that I will identify later. Now I have to go to work

**Comment by n-roman** [comment]
But in repo you have file "bookmark"... strange...

**Comment by n-roman** [comment]
After fixing this imports I have no error anymore, but I said, still don't work. Log after pressing Alt+; :
```
[Extension Host] Congratulations, your extension "metago" is now active!
extensionHost.ts:284 [Extension Host] metago:TypeError: Cannot read property 'then' of undefined
```
I will keep in touch after several hours

**Comment by metasong** [comment]
i've tried to fix this 2 problems in new version.
have a try. 
thanks @n-roman

**Comment by OldViking** [comment]
For me problem is't fixed. I have same warning message, but now nave no errors in developer tools.

**Comment by metasong** [comment]
@OldViking , your problem is because the amVim plugin. that extensionregister the vscode 'type' command on startup, and never release it. while metaGo just dynamicly register this command when needed. but at the same time, vscode only allow one register on that command, that means when metaGo try to register that command, it will fail. currently there is no solution for this problem, maybe we should submit a bug to amVim and other Vim like extension, and let them also do dynamic command using for the 'type' command. 
now you have to make a choice, the two can not coexist.

**Comment by OldViking** [comment]
I do not agree that this is a problem with amVim. Now i have only one extension, which is MetaGo, and it's still no working.

**Comment by metasong** [comment]
@OldViking what your current problem now, can you give me more information: the message on status bar, the log in console, and the environment, and any config about metago, have you tried restart vscode after uninstall other extension i.e. amVim.

my current environment is windows 10 and vscode 1.11.2, and it works fine.

**Comment by OldViking** [comment]
@metasong, i have no problem with MetaGo now, it's working as expected. Only with vim-like extensions. 

Thank you, @metasong, for resolving my problem.

**Comment by n-roman** [comment]
It works! Thank you, @metasong, for fix and for excellent extension!

**Comment by metasong** [comment]
@n-roman and @OldViking, so glad to hear the goog news from you two.
currently i am try a new feature to navigate between files: mark. alt+' to set/unset mark,  alt+/ to list mark and navigate. i.e. after show the list, press c then press enter to clear marks in current file, n to goto next mark, p to go to ptevious one.
if you like you can have a try, it included in the new version. cheers！

**Comment by metasong** [comment]
@n-roman and @OldViking, so glad to hear the goog news from you two.
currently i am try a new feature to navigate between files: mark. alt+' to set/unset mark,  alt+/ to list mark and navigate. i.e. after show the list, press c then press enter to clear marks in current file, n to goto next mark, p to go to ptevious one.
if you like you can have a try, it included in the new version. cheers！
