### ISSUE TITLE
[Feature Request] Multi-Doc jump :)

### ISSUE THREAD

**Issue by dunkarooftop** [metaseed/metaGo#30]
In Emacs there is a package call "Avy" It can jump to all the docs on screen which is a super fast way to switch window. See image :)

https://i.imgur.com/H0vg3Gf.png

Not sure if it's possible to do in VSCode. Thanks for the good work. After trying all the jumpy stuff in VSCode, yours is the best.

**Comment by metasong** [comment]
let me have a look

**Comment by metasong** [comment]
it should be possible, add it to todo list. current you could use Ctrl+1 or Ctrl+2 ... to switch the panel, and then use metajump at the active window.

**Comment by metasong** [comment]
done with version 3.1.2
