### ISSUE TITLE
metago does not work in jupyter notebook mode in VS Code

### ISSUE THREAD

**Issue by dinesh3434** [metaseed/metaGo#31]
Metogo does not seem to be working when I am in Jupyter (.ipynb) notebook in VS Code. Let me know if I am missing any settings or if it is a limitation of metago. Let me know if you need more information regarding the same

**Comment by nicchristeller** [comment]
The jumping is broken in recent versions of VSCode (confirmed in 1.40), see #28. Is this your issue?

**Comment by dinesh3434** [comment]
No. I issue is that Metogo does not work in a Jupyter notebook i.e when you open any *.ipynb in VSCode. Let me know if you need any other details regarding the same.

**Comment by Joker0824** [comment]
the plugins is not work in recent version

**Comment by metasong** [comment]
@dinesh3434 It seems with the Python extension installed the .jpynb would be opened in a kind of custom view, I'll keep an eye on this, to see whether there is a way to let vscode extension works on other extension's view
