### ISSUE TITLE
Keybinding for metaGo.selectLineUp conflicts with default for editor.action.selectHighlights

### ISSUE THREAD

**Issue by Ranguna** [metaseed/metaGo#40]
At least on Linux, the default keybind for `editor.action.selectHighlights` is `Ctrl+Shift+L`, which metaGo inconsiderately overwrites.
Is it possible for the default keybind for `metaGo.selectLineUp` (or any other metaGo commands) to change, so it doesn't conflict with any default vscode commands ?

**Comment by metasong** [comment]
I really want to remove the defaut conflict, the problem here is what's the most convent shortcut for us to use the commands. Is ctrl+l, down, down....for selecting down, and ctrl+l, up,up... for select up ok? are there better way? what's your suggestion.

**Comment by Ranguna** [comment]
By `Ctrl+L, up`, do you mean first `Ctrl+L` (then release) then `up` ?

Because if so, the user would need to constantly press and release `Ctrl+L` before every `up` to select a line up, I think this would be a little slow.

How about `Alt+Shif+K` for up and `Alt+Shift+J` for down instead ?
This follows the classic vim keybind for up and down.

**Comment by metasong** [comment]
I'm thinking make Ctrl+L into a line comand trigger: if the user press i(means up, configurable), triggers the selecting up subcomand, in this subcomand the user can press i again or press k (mean down) several times. Ctrl+L, k is select down subcomand triger. any other key other than i,k would escape this comand. This is the idea, I would evelate the possiblility to make it happen. any better idea?

**Comment by metasong** [comment]
#26

**Comment by Ranguna** [comment]
From what I understand of command triggers, we need to press the trigger (`Ctrl+L`), release the keys and press the next key and release. To repeat the command, you need to do everything else again and not just the last key:
Press `Ctrl+L`, release `Ctrl+L`, press `up`, release `up` -> Select line up is ran.
Press `Ctrl+L`, release `Ctrl+L`, press `up`, release `up` -> Select line up is ran. -> press `up`, release `up` -> Select line up is not ran and the previous selection is removed because the user pressed `up` which caused the cursor to go up (default action for `up` is `cursorUp`).

Press `Ctrl+L`, release `Ctrl+L`, press `up`, release `up` -> Select line up is ran. -> Press `Ctrl+L`, release `Ctrl+L`, press `up`, release `up` -> Select line up is ran again.

The forces the user to keep pressing and releasing `Ctrl+L` and then pressing and releasing `up` to select the line up.

But to tell you the truth, I don't really see any benefit in having this command. We can just use the normal `Shift+up` to select the line up and `Home` while holding `Shift` to select until the start of the line.

**Comment by metasong** [comment]
thank you for your detail description.
in vscode, we could create a command that last for a while, and when execute the command, we can read the user's key stroke and do task accordingly.
the only one problem in my idea is the escape of the command. I could make the escape occurs when user type key that is not 'i' or 'k', and also add a timeout after user press 'i' or 'k' to do escape, it's a kind of over engineering, but opens an opportunity to other line related commands(Ctrl+L, 'key'): search-in-line?.....

for now, I prefer leave this feature with a low priority. 

and consider other shortcut to avoid the collision

**Comment by Ranguna** [comment]
Yes. Maybe to quickly close this issue, you can just assign a non conflicting shortcut, then you can explore other options in the future.
As I said above, `Alt+Shif+K` for up and `Alt+Shift+J` for down are good for me.

**Comment by metasong** [comment]
I prefer to keep use the current default setting; Ctrl+L is the default shortcut for select line down.
you could press ctrl+K, ctrl+s and search metago, find the command and assign the shortcut that you like. note: you could also right click and select delete, to remove the metago default assignment:
![image](https://user-images.githubusercontent.com/5009757/76229581-7323e900-61f0-11ea-9b1b-bb334f2ef6d4.png)

**Comment by Ranguna** [comment]
Yes, I locally deleted metago keybinding before posting this issue.
That new key is fine by me as long as it doesn't overwrite vscode's default ones 👍

**Comment by metasong** [comment]
@Ranguna new implementation:
* <kbd>Ctrl</kbd>+<kbd>l</kbd> to select current line or extend selection by one line below.
* <kbd>Ctrl</kbd>+<kbd>o</kbd> to extend selection by one line above.
> note: <kbd>Ctrl</kbd>+<kbd>o</kbd> triggers open file by default, and it triggers extend line selection when there is selection in active editor.

> if you want to select line up, you should press <kbd>Ctrl</kbd>+<kbd>l</kbd> to select current line and then press <kbd>Ctrl</kbd>+<kbd>o</kbd> to extend line selection up.

I have done the implementation, would be released in the next version😉

**Comment by Ranguna** [comment]
So the original issue was about a metaGo keyboard shortcut conflicting with a default vscode one. Your solution is to remove the old conflicting and replace it with a new, even worse and widely used, default vscode keyboard shortcut ?

Should I change the issue name to be more generic, something like "remove all metaGo keyboard shortcut conflict with default vscode keyboard shortcuts", or should I close this issue and open a new one right after ?

I'm sorry to say this but... This is a bad "solution" to this issue.

**Comment by metasong** [comment]
@Ranguna I think you misunderstand what I mean.
there is no conflict after my modification, It's better than my original solution.
the ctrl+o to open a file still works, it just works as the extending selection up when there is selection.

**Comment by metasong** [comment]
let me build a special release for you, have an evaluation:
[v3.6.1](https://github.com/metaseed/metaGo/raw/master/localRelease/metago-3.6.1.vsix)

**Comment by Ranguna** [comment]
> the ctrl+o to open a file still works, it just works as the extending selection up when there is selection.
Hmm.. Now I feel stupid. I'm sorry for what I said.

Users will still see a weird behavior when they have selected something and are trying to open a file though, but either way, the original command doesn't conflict anymore.

Also v3.6.1 works as described. I'm good with closing this issue once the next version has been released. Thanks :+1:

**Comment by metasong** [comment]
I'm glad you accept it. And also to remind if you want you can bind other shortcuts as you described before, just to make sure to remove 'editorHasSelection' condition for 'selectLineUp' to make it works even without selection.(you need edit json file to modify condition). I think the default key bindings are better, the collision is minor than the convenience it brings.

**Comment by metasong** [comment]
close this issue after publish V3.6.6
