### ISSUE TITLE
cursorSpaceWord commands skip over strings.

### ISSUE THREAD

**Issue by phyllisstein** [metaseed/metaGo#43]
👋 Hey there. Thanks so much for your work on this package: MetaGo and MetaJump are a delight, and MetaWord solves what’s easily the most maddening bug in VSCode I’ve ever seen. My only quibble with the latter is that the `cursorSpaceWord` commands skip over strings, rather than jumping to inter-word separators within them.

I double-checked that the behavior I expected was indeed the behavior that’s native to macOS, because it’s hard to remember at this point:

![2020-06-16 23 48 48](https://user-images.githubusercontent.com/2207980/84853144-884cb700-b02c-11ea-928b-d0ff4852fe86.gif)

In TextEdit, the <kbd>⌥</kbd>+<kbd>←</kbd< and <kbd>⌥</kbd>+<kbd>→</kbd> hotkeys hit the forward slash characters in `'impress/scale-up'` and `'impress/step'`; with MetaGo, the caret skips directly from one end of the string literal to the other.

It’s still a welcome change over VSCode’s native behavior, so I’m not gonna complain too loud. But thanks for taking a look.

**Comment by metasong** [comment]
@phyllisstein thank you so much for such detailed feedback with nice gif! 👍
I'm so glad you like the tool. 

if I understand correctly, you are asking the the functionality of  [word commands](https://github.com/metaseed/metaGo/tree/master/src/metaWord#word-commands-to-movecursorselectdelete-by-word).

metaWord defines 3 kinds of words:
|word type|description|
|---|---|
|SpaceWord(BigWord)| characters separated by 'space'('Space' or 'Tab')|
|Word|a group of alphanumeric character with underscore(A-Za-z0-9_) or a group of other symbol characters(i.e. ~!@#$%^&*()-+:;"',.<>/?\[]{})|
|WordPart(SmallWord)| a group of spaces, a part in a group of CamelCase (A-Za-z0-9) characters, a part of '_' connected (A-Za-z0-9) characters, or a group of other symbol characters|


the word-commands currently use the default vscode's internal commands, whose behavior is different for left and right, which makes me pulsed too. I[ described this in the readme](https://github.com/metaseed/metaGo/blob/master/src/metaWord/README.md#word-commands-to-movecursorselectdelete-by-word) and I do have a plan to make the two direction behavior consistent when have time. 

> Note: the space-word commands's design purpose is to moveCursor/select/delete word separated by space

**Comment by phyllisstein** [comment]
🤦 Gah, thank you for so patiently explaining what was, I now see, already patiently explained in the README. That makes perfect sense. I think what got me turned around initially was that the word commands from this package didn't straightforwardly _override_ the built-in commands. They just wound up appearing alongside them:

![2020-06-22 20 03 20@2x](https://user-images.githubusercontent.com/2207980/85346521-b8c8a100-b4c3-11ea-9180-0717caceac9a.png)

Perhaps because the commands aren't namespaced to the package, this was the odd-looking block that I added to `keybindings.json` to get it working:

```json
{
    "key": "alt+left",
    "command": "cursorWordLeft"
  },
  {
    "key": "shift+alt+left",
    "command": "cursorWordLeftSelect"
  },
  {
    "key": "alt+right",
    "command": "cursorWordRight"
  },
  {
    "key": "shift+alt+right",
    "command": "cursorWordRightSelect"
  },
```

Anyway, working great now. Thanks again for your work on this; can't tell you how nice it is to have these commands back (not to mention beginning-/end-of-paragraph jumps!).

**Comment by metasong** [comment]
@phyllisstein so glad you find your solution, 🥂
