### ISSUE TITLE
Transparent overlay over unused variables and constants

### ISSUE THREAD

**Issue by combdn** [metaseed/metaGo#44]
Hey, thanks for the great package.
This is the issue I’ve encountered: overlay becomes transparent when it is located over unused variables and constants (which are greyed out).
![metago-bug 2020-06-19 21_56_39](https://user-images.githubusercontent.com/889260/85171555-e4efe200-b277-11ea-911a-794db2427dcc.gif)

**Comment by metasong** [comment]
this is because the theme or language extension make the unused variable grayed by making it partially transparent. it also makes the text decorator half transparent.

when I have time I would try to find a workaround, for now let keep it as it is.
