### ISSUE TITLE
Save .vscode/bookmarks.json somewhere else

### ISSUE THREAD

**Issue by plievone** [metaseed/metaGo#5]
Hi, could you persist the bookmarks.json in some other location, for example see extension-specific `storagePath` and `workspaceState` in [Extension API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameextensioncontextaspan-classcodeitem-id1016extensioncontextspan). I haven't experimented with those, so don't know how they are affected by editor and extension upgrades.

Currently the booksmarks.json is saved to disk for any workspace that is opened in the editor, even if I rarely use bookmarks.

At the very least it should confirm whether I want to create the file on first use of bookmarks, so that I don't have to .gitignore it everywhere. Thanks!

**Comment by metasong** [comment]
I am rewriting the bookmark releated functions.
currently you can set  'metaGo.bookmark.saveBookmarksInProject' to false in your setting, if you like.
