### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by quhsi** [metaseed/metaGo#50]
Hi, the repository seems to contain git submodules (e.g. for metaJump). However, the access to the submodules seems to be restricted, so `git submodules update --init` fails. Could you please fix that? Thanks!

**Comment by tbenst** [comment]
I think the plugin may be broken due to this issue--can't see any of the metajump commands in VScode

**Comment by metasong** [comment]
the code is in another repo, after I finished the refactor, it would be open again.

**Comment by tbenst** [comment]
Thanks for the update! I’m very happy to hear you’re still working on it. Seems like an amazing project and I appreciate your efforts—they aren’t taken for granted :)

**Comment by kohane27** [comment]
@metasong Is the src code opened yet? I'm trying to solve the issue with [Integration with vscodevim](https://github.com/metaseed/metaGo/issues/83) but [src @ b162f7e](https://github.com/metaseed/metaJump/tree/b162f7e790c94c7064bb8e509862b3d03e03f6d2) leads to an 404 page. I'd appreciate it if you could open the src again. Thanks!
