### ISSUE TITLE
Occurrences in output pane highlighted

### ISSUE THREAD

**Issue by quhsi** [metaseed/metaGo#52]
**Repro steps & actual behavior**

1. Open a new, empty document.
2. Open the output pane and select "Log (Extension Host)".
→ The output pane is filled with much text.
3. Press the shortcut for `metaGo.gotoBefore` and `e`.
→ Several occurrences in the output pane are highlighted.
4. Complete the action by pressing displayed characters.
→ Labels change as usual but no focus jump into the output pane occurs.

**Expected behavior**

Do not search through and highlight anything where focus switch is not supported to.

**Comment by metasong** [comment]
I would fix this problem when have time

**Comment by metasong** [comment]
fixed and available in next release

**Comment by c7hm4r** [comment]
Thanks!

**Comment by quhsi** [comment]
Thanks!
