### ISSUE TITLE
Multiple characters in metajump

### ISSUE THREAD

**Issue by pokey** [metaseed/metaGo#56]
I'm a bit confused about the behaviour of typing multiple characters for metajump.  In the screenshot below, I typed "tak", but as you can see, it is annotating lots of locations that only start with 't', rather than the full prefix, and it is leaving out all the places on the left that actually do start with 'tak'.  Is this expected behaviour?

![image](https://user-images.githubusercontent.com/755842/106399729-57ca5980-6412-11eb-810f-6915250debc7.png)

Fwiw in case you need to see the text under the annotations:

![image](https://user-images.githubusercontent.com/755842/106399739-6284ee80-6412-11eb-9021-04d02827245f.png)

Great plugin tho!

**Comment by metasong** [comment]
let me confirm

**Comment by metasong** [comment]
it's by design, type one char for navigate within paragraph, 2 chars for current doc, 3 chars for all documents.
if you prefer just type one char, there is a config to use:
```json
"metaGo.jumper.commandsToUseSingleTargetChar":["metaGo.gotoSmart", "metaGo.selectSmart"]
```
to make the to commands use single-target-char: show decorations of all potential locations after user type one target char.
