### ISSUE TITLE
[BUG] Ignore case settings

### ISSUE THREAD

**Issue by freMea** [metaseed/metaGo#6]
Hi,

I set `"metaGo.jumper.targetIgnoreCase": "true"` and it doesn't work.

I think the cause would be the setting must be boolean instead of string type. If user forces the boolean type, it doesn't work either.

You should convert this `"metaGo.jumper.findInSelection": "on"` setting to boolean too.

### While we are it

`"metaGo.decoration.backgroundOpacity": "0.7"` why not convert this to decimal type?

Not important and I don't know if you can do something about it, just curious: `"metaGo.decoration.borderColor": "#000"` has no color preview while built-in  VS code setting like

```
"workbench.colorCustomizations": {
   "focusBorder": "#2F75B9",
}
```
has. Maybe there is color type to assign.

Regards

**Comment by metasong** [comment]
i'll have a look at this weekend, thanks @freMea

**Comment by Crazy-Owl** [comment]
I think I've fixed it in https://github.com/metaseed/metaGo/pull/7

**Comment by metasong** [comment]
@Crazy-Owl good job!
