### ISSUE TITLE
Is there a way of enabling jumping to word easily without any other features?

### ISSUE THREAD

**Issue by paprikka** [metaseed/metaGo#71]
Hey, I've been using jumpy for some time, but I prefer the design of your extension (text is much more legible). Thanks for sharing!

Jumping to a given phrase (`alt+/`) is literally the only feature I need. Is there an easy way of enabling `alt+/` exclusively? Having _more_ features actually messes with my workflow a bit:)

**Comment by metasong** [comment]
just use the  MetaJump which is separated from metaGo.
if you want to remove the shortcut of other command from metaJump:
ctrl+K S then search 'xx'
![image](https://user-images.githubusercontent.com/5009757/121240065-94461000-c85f-11eb-9932-8211472339b9.png)
