### ISSUE TITLE
Feature Request: implement "clever-f-like" functionality

### ISSUE THREAD

**Issue by macintacos** [metaseed/metaGo#73]
There's a plugin I use in Vim all the time called [clever-f](https://github.com/rhysd/clever-f.vim), and every time I come back to VSCode I miss it. I wonder if adding something like it here is something that fits with this project.

How I imagine it working is:

- Initiate metaJump, search for a character on-screen, hit "Enter".
- All the characters that match the character remain highlighted (until the user begins typing I guess, or hits "escape").
- Anything you hit "enter" until the mode is cancelled, the cursor moves to the next match on-screen.

Thoughts on implementing something like this?

**Comment by metasong** [comment]
intresting! let me have a look!

**Comment by metasong** [comment]
@macintacos I guest what you want is the command to repeat-forward and repeat-backward.
I'm planning to bind. alt+. two times for repeat last search forward, and alt+, 2 times to repeat last search backword. it also works for the selection and deletes commands

any suggestion?

**Comment by metasong** [comment]
still do not see value, after rethinking. if the user want to goto the location why not directly type the decorators on screen, but type several times to move backword/foreword to that location.
so would not implement this feature.
@macintacos  there may some other use-case, I do not see, if there is, please let me know, I would open this issue for a while
