### ISSUE TITLE
Feature Request: Add licencing terms

### ISSUE THREAD

**Issue by craigjperry2** [metaseed/metaGo#75]
Hey, awesome extension - it's been rock solid for me. It doesn't slow anything down and it just works. Thank you!

Could you declare the licence for the project by adding a licence file to the repository?

**Background**
Some large corporations have rules around what products can be installed on their machines - e.g. they do code reviews and analyse project dependencies etc. etc. partly to make sure they know what code is running in their firm and partly for security analysis. One common step is a licence check for a product and all its dependencies but no licence is declared in this project which means some large firms will block their staff from installing this.

All the best,

Craig

**Comment by metasong** [comment]
@craigjperry2 thank you for your suggestion. I remember it's MIT, but just checked the license file is not there. I would update it as MIT.

**Comment by metasong** [comment]
updated!🥂
