### ISSUE TITLE
Not working when installed along with vscode-emacs-friendly

### ISSUE THREAD

**Issue by ravigadila** [metaseed/metaGo#8]
VS Code Insider 1.15.

**Comment by metasong** [comment]
currently it could coexist with vim plugin, have a try!

**Comment by metasong** [comment]
i have tried with the vscode-emacs, if installed with it, the alt+; shortcut is bond to 'block comment', you should config it in it in keybindings.json
```
    {
        "key": "alt+;",
        "command": "metaGo.goto",
        "when": "editorTextFocus"
    }
```
